[package]
name = "orchai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "1.0.1" }
cosmwasm-storage = { version = "1.2.0" }
cosmwasm-std = { version = "1.2.0" }
thiserror = { version = "1.0.23" }
# using cw20-base contract as library
cw20-base = { version = "1.0.1", features = ["library"] }

cosmwasm-schema = "1.2.0"
schemars = "0.8.3"